# Version of docker-compose.
version: '3'

# Containers we're going to run.
services:
   # Our Phoenix container.
   web:
      # The build parameters for this container.
      build:
         # Here we define that it should build from the current directory.
         context: .
      environment:
         # Variables to connect to our Postgres server.
         PGURL: ecto://postgres:postgres@db/database_name
         PGUSER: postgres
         PGPASSWORD: postgres
         PGDATABASE: url_shortener_dev
         PGPORT: 5432
         # Hostname of our Postgres container.
         PGHOST: db
         MODE: "${MODE}"
      ports:
         # Mapping the port to make the Phoenix app accessible outside of the container.
         - 8080:8080
   db:
      # We use the predefined Postgres image.
      image: postgres:11
      environment:
         # Set user/password for Postgres.
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         # Set a path where Postgres should store the data.
         PGDATA: /var/lib/postgresql/data/pgdata
      restart: always
      #volumes:
      #   - pgdata:/var/lib/postgresql/data
      ports:
        - 5432:5432

# Define the volumes.
volumes:
   pgdata:

